//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitDataAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class metrotransit_dbEntities : DbContext
    {
        public metrotransit_dbEntities()
            : base("name=metrotransit_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agency> agencies { get; set; }
        public virtual DbSet<authenticated_users> authenticated_users { get; set; }
        public virtual DbSet<batch_load_date> batch_load_date { get; set; }
        public virtual DbSet<calendar> calendars { get; set; }
        public virtual DbSet<calendar_dates> calendar_dates { get; set; }
        public virtual DbSet<route_directions> route_directions { get; set; }
        public virtual DbSet<route> routes { get; set; }
        public virtual DbSet<shape> shapes { get; set; }
        public virtual DbSet<stop_times> stop_times { get; set; }
        public virtual DbSet<stop> stops { get; set; }
        public virtual DbSet<trip> trips { get; set; }
    }
}
