//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitDataAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class route_directions
    {
        public string route_id { get; set; }
        public string direction_long { get; set; }
        public string direction_short { get; set; }
    }
}
