//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitDataAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stop
    {
        public int stop_id { get; set; }
        public string stop_name { get; set; }
        public string stop_desc { get; set; }
        public string stop_lat { get; set; }
        public string stop_lon { get; set; }
        public string stop_street { get; set; }
        public string stop_city { get; set; }
        public string stop_region { get; set; }
        public string stop_postcode { get; set; }
        public string stop_country { get; set; }
        public string zone_id { get; set; }
        public Nullable<int> wheelchair_boarding { get; set; }
        public string stop_url { get; set; }
    }
}
