//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitDataAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        public string route_id { get; set; }
        public string service_id { get; set; }
        public string trip_id { get; set; }
        public string trip_headsign { get; set; }
        public Nullable<int> block_id { get; set; }
        public Nullable<int> shape_id { get; set; }
        public Nullable<bool> wheelchair_accessible { get; set; }
    }
}
